import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'remixicon/fonts/remixicon.css';
import '@/app/assets/css/bootstrap.min.css';
import '@/app/assets/css/app.min.css';
import '@/app/assets/css/custom.css';
import '@/app/assets/css/jsvectormap.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body data-topbar="colored" data-layout="horizontal">
        {children}
      </body>
    </html>
  );
}
